version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Europe/Rome"
  - package-ecosystem: pip
    directory: "/{{cookiecutter.project_slug}}"
    schedule:
      interval: daily
      time: "16:18"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 15
