version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Europe/Rome"
  - package-ecosystem: pip
    directory: "/new_project_root/.github/workflows"
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Europe/Rome"
  - package-ecosystem: pip
    directory: "/new_project_root"
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Europe/Rome"
