version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "19:05"
      timezone: "Europe/Rome"
  - package-ecosystem: pip
    directory: "/{{cookiecutter.project_slug}}"
    schedule:
      interval: daily
      time: "19:05"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 15
