version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "07:55"
      timezone: "Europe/Rome"
  # - package-ecosystem: github-actions
  #   directory: "/new-project-root"
  #   schedule:
  #     interval: daily
  #     time: "05:00"
  #     timezone: "Europe/Rome"
  # - package-ecosystem: pip
  #   directory: "/new-project-root/.github/workflows"
  #   schedule:
  #     interval: daily
  #     time: "05:00"
  #     timezone: "Europe/Rome"
  - package-ecosystem: pip
    directory: "/new-project-root"
    schedule:
      interval: daily
      time: "07:55"
      timezone: "Europe/Rome"
