version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "11:21"
      timezone: "Europe/Rome"
  - package-ecosystem: pip
    directory: "/newprojectroot/.github/workflows"
    schedule:
      interval: daily
      time: "11:21"
      timezone: "Europe/Rome"
  - package-ecosystem: pip
    directory: "/newprojectroot"
    schedule:
      interval: daily
      time: "11:21"
      timezone: "Europe/Rome"
