extensions = [
  "gfm"  # Enable GitHub Flavored Markdown extensions
]
number = false  # Prevent renumbering ordered lists
# Configure line wrapping (e.g., match your Apheleia arg --wrap "keep")
wrap = "keep"
