include = ["**/*.toml"]

[formatting]
align_comments = false
array_auto_collapse = false
array_auto_expand = false
column_width = 60
compact_arrays = true
indent_string = "  "
inline_table_expand = false
